# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tk7ShBYOL6YtaIB3W8L-kfqQHuBf3Ew1
"""

# Linear Congruential Generator (LCG) implementation
def lcg(seed, a, c, m, n):
    numbers = []
    x = seed
    for _ in range(n):
        x = (a * x + c) % m
        numbers.append(x)
    return numbers

# Parameters for LCG
seed = 42  # Initial seed
a = 1664525  # Multiplier
c = 1013904223  # Increment
m = 2**32  # Modulus
n = 10  # Number of random numbers

# Generate pseudo-random numbers
pseudo_random_numbers = lcg(seed, a, c, m, n)

pseudo_random_numbers


####################
# The Generated output is 
[1083814273,
 378494188,
 2479403867,
 955863294,
 1613448261,
 110225632,
 1921058495,
 508781842,
 3753001289,
 4271921684]

