# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tk7ShBYOL6YtaIB3W8L-kfqQHuBf3Ew1
"""

import random

# Set a seed for reproducibility
random.seed(42)

# Generate a list of 10 pseudo-random numbers between 1 and 100
pseudo_random_numbers = [random.randint(1, 100) for _ in range(10)]

print("Pseudo-Random Numbers:", pseudo_random_numbers)

##############################

Pseudo-Random Numbers: [82, 15, 4, 95, 36, 32, 29, 18, 95, 14]